version: "3"
services:
  personaltech-db:
    image:  postgres
    restart: always 
    ports:
      - "5433:5432"
    environment:
       POSTGRES_PASSWORD: pass123
  personaltech-redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
